### ISSUE TITLE
Pharmacy loose ends

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#232]
## Quick post V1.2, loose ends 

__Background__: before lock/mvdm/vdm vertical including pharmacist which will cover the first standard slice and include a command-line node-based pharmacist roll'n'scroll (list pending etc)

- [ ] SOFTWARE SERVICE In 52 (why?)
- [ ] Prescription 52
   - [ ] rx # source
   - [ ] assert why it's IEN keeps going up (ie/ not from 1)
   - [ ] package value generation (and gets updated)
   - [ ] Costing information including _fill cost_ and _daws_ - was filled in in basic version but not now
- [ ] allowed to write med order in User 200
  - [ ] does CPRS stop (isolate RPC) ... OP only or stops NVA too?
  - [ ] portable way to set this field
- [ ] VDM spec covers through discontinue
   - [ ] discontinue and send
   - [ ] 
- [ ] VDM M Pharmacist and VDM must be sync (add to strict asserts for Order/52)
- [ ] MVDM defn covers through discontinue for OP slice
- [ ] narrow STANDARD slice from clone to match the code covered
- [ ] NVA spec break out to match op and fix it
- [ ] MVDM defn expanded for NVA

**Comment by conorcaregraf** [comment]
## From Allergies

link of 50.67 trhough 50.68 multiple. Is this a problem with VDM or because of new Pharmacy meta

```text
1.2 yields bug as OSEHRA changed ...

```text
vdp@addgene-ubuntu-1604-vbox:~/VDM/prototypes/allergies$ ./runRPCAllergies-spec.sh 
Running tests over rpc runner ...
Started
.................


17 specs, 0 failures
Finished in 0.722 seconds

Running tests over cRPCL ...
Started
.......F...F.....

Failures:
1) testAllergyRPCs Create Historical NDC/UPN 50.67 Allergy - will expect equivalent 50.6 to be created in its stead
  Message:
    Error: Property with fmId 1 is not in model for class Reduced_Copay-50_6845
  Stack:
    Error: Property with fmId 1 is not in model for class Reduced_Copay-50_6845
        at /home/vdp/VDM/prototypes/fmql.js:149:23
        at Array.forEach (native)
        at /home/vdp/VDM/prototypes/fmql.js:140:29
        at Array.forEach (native)
        at toJSON (/home/vdp/VDM/prototypes/fmql.js:130:13)
        at /home/vdp/VDM/prototypes/fmql.js:160:30
        at Array.forEach (native)
        at /home/vdp/VDM/prototypes/fmql.js:140:29
        at Array.forEach (native)
        at Object.toJSON (/home/vdp/VDM/prototypes/fmql.js:130:13)

2) testAllergyRPCs EIE an historical allergy and see side effect document
  Message:
    Error: No such identifier for type 120_8
  Stack:
    Error: No such identifier for type 120_8
        at /home/vdp/VDM/prototypes/mvdm.js:498:19
        at Array.forEach (native)
        at MVDM._describe (/home/vdp/VDM/prototypes/mvdm.js:490:16)
        at MVDM.remove (/home/vdp/VDM/prototypes/mvdm.js:248:30)
        at Object.processRPCInvocation (/home/vdp/VDM/prototypes/allergies/rpcLAllergiesModel.js:290:29)
        at ClinicalRPCLocker.run (/home/vdp/VDM/prototypes/cRPCL.js:31:39)
        at RPCFacade.run (/home/vdp/VDM/prototypes/rpcFacade.js:122:35)
        at Object.<anonymous> (/home/vdp/VDM/prototypes/allergies/rpcAllergies-spec.js:667:31)

17 specs, 2 failures
Finished in 3.539 seconds
```

**Comment by conorcaregraf** [comment]
## Auto complete

Nancy Auto Finish - see 

> The Autofinish Rx and Prescription Printing/Faxing project adds functionality to Vista Office EHR (VOE) to allow automatic finishing of a medication order and printing or faxing of a prescription. When the order is signed by a provider in CPRS, the prescription can be given to a patient for filling at a pharmacy or faxed to that pharmacy. No modifications were made to CPRS Delphi code.

> VistA was not designed to provide this functionality when originally developed. 

> Modification of current PSO* M code to automate the finishing process and then to print or fax the prescription. The advantage to this approach was retention of all business rules, auditing, and other functionality of the PSO* code as it exists, with retention of future code. The downside of this approach was the compromising of some desired functionality in Autofinish Rx and the maintenance of the associated PSO* code. This was the option that was chosen.

(pathway to auto may be used by me ... see controlled by configs ... gotta see. but may not be in current?)

**Comment by conorcaregraf** [comment]
From Rafael

In the process of building out the OP Pharmacy read/write, are you coming across any potential hooks to do prescription monitoring  (max daily dose; max monthly dose, etc.) 

Use case:  Prescription monitoring for Opiods.

**Comment by conorcaregraf** [comment]
From OSEHRA submissions 

> A new comment has been added to OSEHRA Technical Journal submission: VA Code In Flight Submission - One VA Pharmacy Clinical Ancillary Services (CAS) Medication Permissions and Dispensing Upgrades (MPDU) PSO*7*497 and PSS*1*212.

and review more ... could be used for Build 3 is pharmacy work continues.
